name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: "twaindoccano"
  CONTAINER_REGISTRY_URI: "twainglobalacr.azurecr.io"

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: 'prd'

    steps:
      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      # Setup Docker buildx
      - name: Setup Docker buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v1
      
      # Setup QUEMU
      - name: Set up QEMU
        id: docker_quemu
        uses: docker/setup-qemu-action@v1
      
      # Log in to container registry
      - name: Log into container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URI }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.CONTAINER_REGISTRY_URI }}/${{ env.IMAGE_NAME }}
          tag-sha: false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          # tag-semver: |
          #   {{version}}
          #   {{major}}.{{minor}}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
